sonar.projectKey=home-stock
sonar.projectName=HomeStock
sonar.projectVersion=1.0

# Specify the source directory (if needed)
sonar.sources=src  # or '.' for root directory, or specific paths

# SonarQube host URL
sonar.host.url=http://localhost:9000  # Or https://sonarcloud.io for SonarCloud

# Authentication token (if needed)
sonar.login=sqa_ef3f8b7083ed5ccf5eede7e453a9cd61363dc0c9
